# Enhanced training data with more examples and better coverage
training_data = [
    # Earning (1) - 10 examples
    ("What are the earnings?", 1),
    ("Show me profit margins for this year", 1),
    ("Revenue growth analysis report", 1),
    ("Quarterly earnings statement", 1),
    ("Net income and earnings data", 1),
    ("Total earnings calculation for 2024", 1),
    ("Profit and loss earnings overview", 1),
    ("Financial earnings summary", 1),
    ("Annual earnings performance", 1),
    ("Earnings per share information", 1),
    
    # Business (2) - 10 examples
    ("Business strategy and planning", 2),
    ("Company performance metrics dashboard", 2),
    ("Market share analysis and report", 2),
    ("Business development plans for next year", 2),
    ("Corporate governance policies", 2),
    ("Business operations review meeting", 2),
    ("Strategic business planning session", 2),
    ("Business model analysis document", 2),
    ("Competitive business analysis report", 2),
    ("Business intelligence data insights", 2),
    
    # Safety (3) - 10 examples
    ("Safety protocols and procedures", 3),
    ("Risk assessment procedures manual", 3),
    ("Security measures implementation guide", 3),
    ("Compliance requirements checklist", 3),
    ("Emergency procedures documentation", 3),
    ("Workplace safety guidelines handbook", 3),
    ("Safety training materials and resources", 3),
    ("Risk management framework overview", 3),
    ("Health and safety regulations compliance", 3),
    ("Safety inspection report findings", 3),
    
    # Quarterly earning (4) - 10 examples
    ("Quarterly earnings performance report", 4),
    ("Q2 earnings results and analysis", 4),
    ("Quarterly revenue report summary", 4),
    ("Three-month earnings performance", 4),
    ("Quarterly profit analysis data", 4),
    ("Quarterly financial results overview", 4),
    ("Earnings for last quarter review", 4),
    ("Quarterly income statement details", 4),
    ("Q3 earnings forecast projection", 4),
    ("Quarterly earnings growth trends", 4),
    
    # Daily earning (5) - 10 examples
    ("Daily earnings report summary", 5),
    ("Today's revenue numbers update", 5),
    ("Daily profit calculation results", 5),
    ("Earnings for today's performance", 5),
    ("Daily income summary report", 5),
    ("Today's financial performance metrics", 5),
    ("Daily revenue tracking data", 5),
    ("Profit for the day analysis", 5),
    ("Daily earnings analysis review", 5),
    ("Today's earnings data insights", 5),
    
    # Improve earning (6) - 10 examples
    ("How to improve earnings performance", 6),
    ("Strategies to increase revenue growth", 6),
    ("Ways to boost profits and earnings", 6),
    ("Earnings enhancement techniques guide", 6),
    ("Profit improvement methods overview", 6),
    ("Increase quarterly earnings strategies", 6),
    ("Boost daily revenue approaches", 6),
    ("Earnings optimization strategies plan", 6),
    ("Improve financial performance methods", 6),
    ("Revenue growth tactics implementation", 6),
    
    # Growth (7) - 10 examples
    ("Business growth analysis report", 7),
    ("Revenue growth trends overview", 7),
    ("Growth strategy planning session", 7),
    ("Market growth opportunities analysis", 7),
    ("Financial growth metrics dashboard", 7),
    ("Growth rate calculation methodology", 7),
    ("Expansion growth plans development", 7),
    ("Sustainable growth strategies framework", 7),
    ("Growth projection analysis report", 7),
    ("Organic growth initiatives planning", 7),
    
    # Weather (8) - 10 examples
    ("Weather forecast for today", 8),
    ("What's the weather like outside", 8),
    ("Temperature for tomorrow prediction", 8),
    ("Weather conditions report update", 8),
    ("Rain forecast for this week", 8),
    ("Weather update please provide", 8),
    ("Current weather conditions overview", 8),
    ("Weather outlook for the weekend", 8),
    ("Humidity and temperature data report", 8),
    ("Weather prediction for travel planning", 8),
    
    # Others - 15 examples
    ("Hello how are you doing today", "default"),
    ("What time is it right now", "default"),
    ("Tell me a funny joke please", "default"),
    ("How is your day going so far", "default"),
    ("What can you help me with today", "default"),
    ("Introduce yourself and your capabilities", "default"),
    ("Who created you and why", "default"),
    ("What is your purpose and function", "default"),
    ("How does this system work exactly", "default"),
    ("Thank you for your help and assistance", "default"),
    ("Good morning how are you today", "default"),
    ("Can you tell me about yourself", "default"),
    ("What is the meaning of life", "default"),
    ("How old are you in years", "default"),
    ("Where are you located currently", "default"),
]